//Pages
export const GET_PAGE = "GET_PAGE"
export const INIT_PAGE = "INIT_PAGE"


//User log
export const GET_USER_LOADING = "GET_USER_LOADING"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"
export const CHANGE_PASSWORD_USER_LOADING = "CHANGE_PASSWORD_USER_LOADING"
export const CHANGE_PASSWORD_USER_SUCCESS = "CHANGE_PASSWORD_USER_SUCCESS"
export const CHANGE_PASSWORD_USER_ERROR = "CHANGE_PASSWORD_USER_ERROR"
export const INIT_USER = "INIT_USER"


//Gestion utilisateurs
export const GET_USERS_LOADING = "GET_USERS_LOADING"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_ERROR = "GET_USERS_ERROR"
export const EDIT_USER_LOADING = "EDIT_USER_LOADING"
export const EDIT_USER_ERROR = "EDIT_USER_ERROR"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const DELETE_USER_LOADING = "DELETE_USER_LOADING"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const REMOVE_ALL_USERS = "REMOVE_ALL_USERS"


//TypeTubes
export const GET_TYPETUBES_LOADING = "GET_TYPETUBES_LOADING"
export const GET_TYPETUBES_SUCCESS = "GET_TYPETUBES_SUCCESS"
export const GET_TYPETUBES_ERROR = "GET_TYPETUBES_ERROR"
export const GET_TYPETUBES_OREDERABLE_LOADING = "GET_TYPETUBES_OREDERABLE_LOADING"
export const GET_TYPETUBES_OREDERABLE_SUCCESS = "GET_TYPETUBES_OREDERABLE_SUCCESS"
export const GET_TYPETUBES_OREDERABLE_ERROR = "GET_TYPETUBES_OREDERABLE_ERROR"
export const CREATE_TYPETUBE_LOADING = "CREATE_TYPETUBE_LOADING"
export const CREATE_TYPETUBE_SUCCESS = "CREATE_TYPETUBE_SUCCESS"
export const CREATE_TYPETUBE_ERROR = "CREATE_TYPETUBE_ERROR"
export const UPDATE_TYPETUBE_LOADING = "UPDATE_TYPETUBE_LOADING"
export const UPDATE_TYPETUBE_SUCCESS = "UPDATE_TYPETUBE_SUCCESS"
export const UPDATE_TYPETUBE_ERROR = "UPDATE_TYPETUBE_ERROR"
export const DELETE_TYPETUBE_LOADING = "DELETE_TYPETUBE_LOADING"
export const DELETE_TYPETUBE_SUCCESS = "DELETE_TYPETUBE_SUCCESS"
export const DELETE_TYPETUBE_ERROR = "DELETE_TYPETUBE_ERROR"
export const REMOVE_ALL_TYPETUBES = "REMOVE_ALL_TYPETUBES"


//Saisons
export const GET_SAISONS_LOADING = "GET_SAISONS_LOADING"
export const GET_SAISONS_SUCCESS = "GET_SAISONS_SUCCESS"
export const GET_SAISONS_ERROR = "GET_SAISONS_ERROR"
export const GET_SAISON_ACTIVE_LOADING = "GET_SAISON_ACTIVE_LOADING"
export const GET_SAISON_ACTIVE_SUCCESS = "GET_SAISON_ACTIVE_SUCCESS"
export const GET_SAISON_ACTIVE_ERROR = "GET_SAISON_ACTIVE_ERROR"
export const CREATE_SAISON_LOADING = "CREATE_SAISON_LOADING"
export const CREATE_SAISON_SUCCESS = "CREATE_SAISON_SUCCESS"
export const CREATE_SAISON_ERROR = "CREATE_SAISON_ERROR"
export const CREATE_SAISON_CONSOVOLANT_ERROR = "CREATE_SAISON_CONSOVOLANT_ERROR"
export const CREATE_SAISON_CONSOMOIS_ERROR = "CREATE_SAISON_CONSOMOIS_ERROR"
export const UPDATE_SAISON_LOADING = "UPDATE_SAISON_LOADING"
export const UPDATE_SAISON_SUCCESS = "UPDATE_SAISON_SUCCESS"
export const UPDATE_SAISON_ERROR = "UPDATE_SAISON_ERROR"
export const DELETE_SAISON_LOADING = "DELETE_SAISON_LOADING"
export const DELETE_SAISON_SUCCESS = "DELETE_SAISON_SUCCESS"
export const DELETE_SAISON_ERROR = "DELETE_SAISON_ERROR"
export const TRANSFER_SAISON_LOADING = "TRANSFER_SAISON_LOADING"
export const TRANSFER_SAISON_SUCCESS = "TRANSFER_SAISON_SUCCESS"
export const TRANSFER_SAISON_ERROR = "TRANSFER_SAISON_ERROR"
export const REMOVE_SAISON_ACTIVE = "REMOVE_SAISON_ACTIVE"
export const REMOVE_ALL_SAISONS = "REMOVE_ALL_SAISONS"


//ConsoVolants
export const GET_CONSOVOLANTS_LOADING = "GET_CONSOVOLANTS_LOADING"
export const GET_CONSOVOLANTS_SUCCESS = "GET_CONSOVOLANTS_SUCCESS"
export const GET_CONSOVOLANTS_ERROR = "GET_CONSOVOLANTS_ERROR"
export const UPDATE_CONSOVOLANT_LOADING = "UPDATE_CONSOVOLANT_LOADING"
export const UPDATE_CONSOVOLANT_SUCCESS = "UPDATE_CONSOVOLANT_SUCCESS"
export const UPDATE_CONSOVOLANT_ERROR = "UPDATE_CONSOVOLANT_ERROR"
export const UPDATE_CONSOMOIS_CONSOVOLANT = "UPDATE_CONSOMOIS_CONSOVOLANT"
export const DELETE_CONSOVOLANT_LOADING = "DELETE_CONSOVOLANT_LOADING"
export const DELETE_CONSOVOLANT_SUCCESS = "DELETE_CONSOVOLANT_SUCCESS"
export const DELETE_CONSOVOLANT_ERROR = "DELETE_CONSOVOLANT_ERROR"
export const REMOVE_ALL_CONSOVOLANTS = "REMOVE_ALL_CONSOVOLANTS"


//ConsoMois
export const GET_CONSOMOIS_LOADING = "GET_CONSOMOIS_LOADING"
export const GET_CONSOMOIS_SUCCESS = "GET_CONSOMOIS_SUCCESS"
export const GET_CONSOMOIS_ERROR = "GET_CONSOMOIS_ERROR"
export const UPDATE_CONSOMOIS_LOADING = "UPDATE_CONSOMOIS_LOADING"
export const UPDATE_CONSOMOIS_SUCCESS = "UPDATE_CONSOMOIS_SUCCESS"
export const UPDATE_CONSOMOIS_ERROR = "UPDATE_CONSOMOIS_ERROR"
export const DELETE_CONSOMOIS_LOADING = "DELETE_CONSOMOIS_LOADING"
export const DELETE_CONSOMOIS_SUCCESS = "DELETE_CONSOMOIS_SUCCESS"
export const DELETE_CONSOMOIS_ERROR = "DELETE_CONSOMOIS_ERROR"
export const REMOVE_ALL_CONSOMOIS = "REMOVE_ALL_CONSOMOIS"


//Membres
export const GET_MEMBRES_LOADING = "GET_MEMBRES_LOADING"
export const GET_MEMBRES_SUCCESS = "GET_MEMBRES_SUCCESS"
export const GET_MEMBRES_ERROR = "GET_MEMBRES_ERROR"
export const CREATE_MEMBRE_LOADING = "CREATE_MEMBRE_LOADING"
export const CREATE_MEMBRE_SUCCESS = "CREATE_MEMBRE_SUCCESS"
export const CREATE_MEMBRE_ERROR = "CREATE_MEMBRE_ERROR"
export const UPDATE_MEMBRE_LOADING = "UPDATE_MEMBRE_LOADING"
export const UPDATE_MEMBRE_SUCCESS = "UPDATE_MEMBRE_SUCCESS"
export const UPDATE_MEMBRE_ERROR = "UPDATE_MEMBRE_ERROR"
export const DELETE_MEMBRE_LOADING = "DELETE_MEMBRE_LOADING"
export const DELETE_MEMBRE_SUCCESS = "DELETE_MEMBRE_SUCCESS"
export const DELETE_MEMBRE_ERROR = "DELETE_MEMBRE_ERROR"
export const REMOVE_ALL_MEMBRES = "REMOVE_ALL_MEMBRES"


//Prixtubes
export const GET_PRIXTUBES_LOADING = "GET_PRIXTUBES_LOADING"
export const GET_PRIXTUBES_SUCCESS = "GET_PRIXTUBES_SUCCESS"
export const GET_PRIXTUBES_ERROR = "GET_PRIXTUBES_ERROR"
export const CREATE_PRIXTUBE_LOADING = "CREATE_PRIXTUBE_LOADING"
export const CREATE_PRIXTUBE_SUCCESS = "CREATE_PRIXTUBE_SUCCESS"
export const CREATE_PRIXTUBE_ERROR = "CREATE_PRIXTUBE_ERROR"
export const UPDATE_PRIXTUBE_LOADING = "UPDATE_PRIXTUBE_LOADING"
export const UPDATE_PRIXTUBE_SUCCESS = "UPDATE_PRIXTUBE_SUCCESS"
export const UPDATE_PRIXTUBE_ERROR = "UPDATE_PRIXTUBE_ERROR"
export const DELETE_PRIXTUBE_LOADING = "DELETE_PRIXTUBE_LOADING"
export const DELETE_PRIXTUBE_SUCCESS = "DELETE_PRIXTUBE_SUCCESS"
export const DELETE_PRIXTUBE_ERROR = "DELETE_PRIXTUBE_ERROR"
export const REMOVE_ALL_PRIXTUBES = "REMOVE_ALL_PRIXTUBES"


//Commandes
export const GET_COMMANDES_LOADING = "GET_COMMANDES_LOADING"
export const GET_COMMANDES_SUCCESS = "GET_COMMANDES_SUCCESS"
export const GET_COMMANDES_ERROR = "GET_COMMANDES_ERROR"
export const CREATE_COMMANDE_LOADING = "CREATE_COMMANDE_LOADING"
export const CREATE_COMMANDE_SUCCESS = "CREATE_COMMANDE_SUCCESS"
export const CREATE_COMMANDE_ERROR = "CREATE_COMMANDE_ERROR"
export const UPDATE_COMMANDE_LOADING = "UPDATE_COMMANDE_LOADING"
export const UPDATE_COMMANDE_SUCCESS = "UPDATE_COMMANDE_SUCCESS"
export const UPDATE_COMMANDE_ERROR = "UPDATE_COMMANDE_ERROR"
export const DELETE_COMMANDE_LOADING = "DELETE_COMMANDE_LOADING"
export const DELETE_COMMANDE_SUCCESS = "DELETE_COMMANDE_SUCCESS"
export const DELETE_COMMANDE_ERROR = "DELETE_COMMANDE_ERROR"
export const REMOVE_ALL_COMMANDES = "REMOVE_ALL_COMMANDES"


//Competitions
export const GET_COMPETITIONS_LOADING = "GET_COMPETITIONS_LOADING"
export const GET_COMPETITIONS_SUCCESS = "GET_COMPETITIONS_SUCCESS"
export const GET_COMPETITIONS_ERROR = "GET_COMPETITIONS_ERROR"
export const CREATE_COMPETITION_LOADING = "CREATE_COMPETITION_LOADING"
export const CREATE_COMPETITION_SUCCESS = "CREATE_COMPETITION_SUCCESS"
export const CREATE_COMPETITION_ERROR = "CREATE_COMPETITION_ERROR"
export const UPDATE_COMPETITION_LOADING = "UPDATE_COMPETITION_LOADING"
export const UPDATE_COMPETITION_SUCCESS = "UPDATE_COMPETITION_SUCCESS"
export const UPDATE_COMPETITION_ERROR = "UPDATE_COMPETITION_ERROR"
export const DELETE_COMPETITION_LOADING = "DELETE_COMPETITION_LOADING"
export const DELETE_COMPETITION_SUCCESS = "DELETE_COMPETITION_SUCCESS"
export const DELETE_COMPETITION_ERROR = "DELETE_COMPETITION_ERROR"
export const REMOVE_ALL_COMPETITIONS = "REMOVE_ALL_COMPETITIONS"


//Stock
export const INIT_STOCKS = "INIT_STOCKS"
export const SET_STOCK = "SET_STOCK"
export const ADD_STOCK = "ADD_STOCK"


//Restocks
export const GET_RESTOCKS_LOADING = "GET_RESTOCKS_LOADING"
export const GET_RESTOCKS_SUCCESS = "GET_RESTOCKS_SUCCESS"
export const GET_RESTOCKS_ERROR = "GET_RESTOCKS_ERROR"
export const CREATE_RESTOCK_LOADING = "CREATE_RESTOCK_LOADING"
export const CREATE_RESTOCK_SUCCESS = "CREATE_RESTOCK_SUCCESS"
export const CREATE_RESTOCK_ERROR = "CREATE_RESTOCK_ERROR"
export const REMOVE_ALL_RESTOCKS = "REMOVE_ALL_RESTOCKS"